/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import type { getRouter } from './router.tsx'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as authedAdminInvitesRouteImport } from './routes/(authed)/admin/invites'
import { Route as authedAdminRouteRouteImport } from './routes/(authed)/admin/route'
import { Route as authedAdminUsersRouteImport } from './routes/(authed)/admin/users'
import { Route as authedCalculatorIndexRouteImport } from './routes/(authed)/calculator/index'
import { Route as authedCardsIdRouteImport } from './routes/(authed)/cards/$id'
import { Route as authedCardsIndexRouteImport } from './routes/(authed)/cards/index'
import { Route as authedIndexRouteImport } from './routes/(authed)/index'
import { Route as authedProfileIndexRouteImport } from './routes/(authed)/profile/index'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as authedSessionsIdRouteImport } from './routes/(authed)/sessions/$id'
import { Route as authedSessionsIdEditRouteImport } from './routes/(authed)/sessions/$id.edit'
import { Route as authedSessionsIndexRouteImport } from './routes/(authed)/sessions/index'
import { Route as authedSessionsNewRouteImport } from './routes/(authed)/sessions/new'
import { Route as rootRouteImport } from './routes/__root'
import type { startInstance } from './start.tsx'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authedIndexRoute = authedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authedAdminRouteRoute = authedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSessionsIndexRoute = authedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedProfileIndexRoute = authedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedCardsIndexRoute = authedCardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedCalculatorIndexRoute = authedCalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSessionsNewRoute = authedSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSessionsIdRoute = authedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedCardsIdRoute = authedCardsIdRouteImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedAdminUsersRoute = authedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authedAdminRouteRoute,
} as any)
const authedAdminInvitesRoute = authedAdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => authedAdminRouteRoute,
} as any)
const authedSessionsIdEditRoute = authedSessionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => authedSessionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof authedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof authedIndexRoute
  '/admin/invites': typeof authedAdminInvitesRoute
  '/admin/users': typeof authedAdminUsersRoute
  '/cards/$id': typeof authedCardsIdRoute
  '/sessions/$id': typeof authedSessionsIdRouteWithChildren
  '/sessions/new': typeof authedSessionsNewRoute
  '/calculator/': typeof authedCalculatorIndexRoute
  '/cards/': typeof authedCardsIndexRoute
  '/profile/': typeof authedProfileIndexRoute
  '/sessions/': typeof authedSessionsIndexRoute
  '/sessions/$id/edit': typeof authedSessionsIdEditRoute
}
export interface FileRoutesByTo {
  '/admin': typeof authedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/': typeof authedIndexRoute
  '/admin/invites': typeof authedAdminInvitesRoute
  '/admin/users': typeof authedAdminUsersRoute
  '/cards/$id': typeof authedCardsIdRoute
  '/sessions/$id': typeof authedSessionsIdRouteWithChildren
  '/sessions/new': typeof authedSessionsNewRoute
  '/calculator': typeof authedCalculatorIndexRoute
  '/cards': typeof authedCardsIndexRoute
  '/profile': typeof authedProfileIndexRoute
  '/sessions': typeof authedSessionsIndexRoute
  '/sessions/$id/edit': typeof authedSessionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(authed)': typeof authedRouteRouteWithChildren
  '/(authed)/admin': typeof authedAdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(authed)/': typeof authedIndexRoute
  '/(authed)/admin/invites': typeof authedAdminInvitesRoute
  '/(authed)/admin/users': typeof authedAdminUsersRoute
  '/(authed)/cards/$id': typeof authedCardsIdRoute
  '/(authed)/sessions/$id': typeof authedSessionsIdRouteWithChildren
  '/(authed)/sessions/new': typeof authedSessionsNewRoute
  '/(authed)/calculator/': typeof authedCalculatorIndexRoute
  '/(authed)/cards/': typeof authedCardsIndexRoute
  '/(authed)/profile/': typeof authedProfileIndexRoute
  '/(authed)/sessions/': typeof authedSessionsIndexRoute
  '/(authed)/sessions/$id/edit': typeof authedSessionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/register'
    | '/'
    | '/admin/invites'
    | '/admin/users'
    | '/cards/$id'
    | '/sessions/$id'
    | '/sessions/new'
    | '/calculator/'
    | '/cards/'
    | '/profile/'
    | '/sessions/'
    | '/sessions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/register'
    | '/'
    | '/admin/invites'
    | '/admin/users'
    | '/cards/$id'
    | '/sessions/$id'
    | '/sessions/new'
    | '/calculator'
    | '/cards'
    | '/profile'
    | '/sessions'
    | '/sessions/$id/edit'
  id:
    | '__root__'
    | '/(auth)'
    | '/(authed)'
    | '/(authed)/admin'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(authed)/'
    | '/(authed)/admin/invites'
    | '/(authed)/admin/users'
    | '/(authed)/cards/$id'
    | '/(authed)/sessions/$id'
    | '/(authed)/sessions/new'
    | '/(authed)/calculator/'
    | '/(authed)/cards/'
    | '/(authed)/profile/'
    | '/(authed)/sessions/'
    | '/(authed)/sessions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  authedRouteRoute: typeof authedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/': {
      id: '/(authed)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authedIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(authed)/admin': {
      id: '/(authed)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authedAdminRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/sessions/': {
      id: '/(authed)/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof authedSessionsIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/profile/': {
      id: '/(authed)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof authedProfileIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/cards/': {
      id: '/(authed)/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof authedCardsIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/calculator/': {
      id: '/(authed)/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof authedCalculatorIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/sessions/new': {
      id: '/(authed)/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof authedSessionsNewRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/sessions/$id': {
      id: '/(authed)/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof authedSessionsIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/cards/$id': {
      id: '/(authed)/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof authedCardsIdRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/admin/users': {
      id: '/(authed)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof authedAdminUsersRouteImport
      parentRoute: typeof authedAdminRouteRoute
    }
    '/(authed)/admin/invites': {
      id: '/(authed)/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof authedAdminInvitesRouteImport
      parentRoute: typeof authedAdminRouteRoute
    }
    '/(authed)/sessions/$id/edit': {
      id: '/(authed)/sessions/$id/edit'
      path: '/edit'
      fullPath: '/sessions/$id/edit'
      preLoaderRoute: typeof authedSessionsIdEditRouteImport
      parentRoute: typeof authedSessionsIdRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren =
  authRouteRoute._addFileChildren(authRouteRouteChildren)

interface authedAdminRouteRouteChildren {
  authedAdminInvitesRoute: typeof authedAdminInvitesRoute
  authedAdminUsersRoute: typeof authedAdminUsersRoute
}

const authedAdminRouteRouteChildren: authedAdminRouteRouteChildren = {
  authedAdminInvitesRoute: authedAdminInvitesRoute,
  authedAdminUsersRoute: authedAdminUsersRoute,
}

const authedAdminRouteRouteWithChildren = authedAdminRouteRoute._addFileChildren(
  authedAdminRouteRouteChildren
)

interface authedSessionsIdRouteChildren {
  authedSessionsIdEditRoute: typeof authedSessionsIdEditRoute
}

const authedSessionsIdRouteChildren: authedSessionsIdRouteChildren = {
  authedSessionsIdEditRoute: authedSessionsIdEditRoute,
}

const authedSessionsIdRouteWithChildren = authedSessionsIdRoute._addFileChildren(
  authedSessionsIdRouteChildren
)

interface authedRouteRouteChildren {
  authedAdminRouteRoute: typeof authedAdminRouteRouteWithChildren
  authedIndexRoute: typeof authedIndexRoute
  authedCardsIdRoute: typeof authedCardsIdRoute
  authedSessionsIdRoute: typeof authedSessionsIdRouteWithChildren
  authedSessionsNewRoute: typeof authedSessionsNewRoute
  authedCalculatorIndexRoute: typeof authedCalculatorIndexRoute
  authedCardsIndexRoute: typeof authedCardsIndexRoute
  authedProfileIndexRoute: typeof authedProfileIndexRoute
  authedSessionsIndexRoute: typeof authedSessionsIndexRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedAdminRouteRoute: authedAdminRouteRouteWithChildren,
  authedIndexRoute: authedIndexRoute,
  authedCardsIdRoute: authedCardsIdRoute,
  authedSessionsIdRoute: authedSessionsIdRouteWithChildren,
  authedSessionsNewRoute: authedSessionsNewRoute,
  authedCalculatorIndexRoute: authedCalculatorIndexRoute,
  authedCardsIndexRoute: authedCardsIndexRoute,
  authedProfileIndexRoute: authedProfileIndexRoute,
  authedSessionsIndexRoute: authedSessionsIndexRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  authedRouteRoute: authedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
